server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${APP_SECRET:ceposto2021}
  connectors:
    userRegistrationConnector: ${USER_REGISTRATION:"user_service:8080/api/user/register"}




spring:
  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:ceposto2021}

