server:
  port: ${PORT:8080}

app:
  jwt:
    secret: ${APP_SECRET:ceposto2021}
  connectors:
    userServiceBaseUrl: ${USER_SERVICE_HOST:"user_service:8080"}
    merchantServiceBaseUrl: ${MERCHANT_SERVICE_HOST:"merchant_service:8080"}
    prenotationServiceBaseUrl: ${PRENOTATION_SERVICE_HOST:"prenotation_service:8080"}

google:
  client:
    id: ${GOOGLE_CLIENT_ID:531289078330-k61rsekikad4c5l3i7oaq44sagcj1e9l.apps.googleusercontent.com}

spring:
  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST}:${DB_PORT}/${DB_NAME:ceposto}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:ceposto2021}
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        id:
          new_generator_mappings: false